# Generated by Django 5.0.3 on 2024-03-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usercritics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='critic',
            name='movie_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
