# Generated by Django 5.0.3 on 2024-03-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usercritics', '0002_critic_movie_title_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='critic',
            name='creator_first_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='critic',
            name='creator_last_name',
            field=models.CharField(default=(), max_length=255),
            preserve_default=False,
        ),
    ]
